apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1cfm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1cfm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1cfm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1cfm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1cfm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efpn-tenant/rhtap-demo-app/hacbs-test-project-1cfm@sha256:1085887c51b7e501716caf914d7903f9396eee103d44781f5c7fe387e7410757
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
