apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1cfm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efpn-tenant/rhtap-demo-app/hacbs-test-project-1cfm@sha256:7c648a63955d39fe4b0097c84b83e83ce2a0c80d9fed28f3af1ea5d5f2c92309
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
