apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1cfm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-efpn-tenant/rhtap-demo-app/hacbs-test-project-1cfm@sha256:1085887c51b7e501716caf914d7903f9396eee103d44781f5c7fe387e7410757
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
